name: Maven Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run tests
      run: mvn -B test
    
    - name: Generate test report
      run: mvn -B surefire-report:report
      
    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: target/site/surefire-report.html
        
    - name: Archive compiled JAR
      uses: actions/upload-artifact@v3
      with:
        name: flashcard-app
        path: target/*.jar